#!/usr/bin/env python
# encoding: utf-8

#
# SPDX-FileCopyrightText: Copyright © 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Théophile Gentilhomme <theophile.gentilhomme@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
#
# anonymization: Text ner and pii
#

import argparse
import json

from anonymization.pii.config import gen_default_config
from anonymization.api import load_and_anonymize


if __name__ == "__main__":
    """
    Anonymize Personally Identifiable Information (PII) in a file using the provided configuration.

    This script allows users to anonymize PII in a file of supported formats (txt, csv, xlsx) using
    the provided configuration for anonymization.

    Usage:
        python script_name.py [-h] [-c CONFIG] -f FILE

    Arguments:
        -h, --help      : Show help message and exit.
        -c CONFIG       : Configuration file (in JSON format) for anonymization.
                          If not provided, the default configuration will be used.
        -f FILE         : File to anonymize. Supported file formats include txt, csv, and xlsx.

    Example Usage:
        # Anonymize PII in a CSV file using default configuration
        anonymize -f input_file.csv

        # Anonymize PII in a TXT file using a custom configuration file
        anonymize -f input_file.txt -c custom_config.json
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-c",
        "--config",
        default=None,
        help="Configuration file for anonymization",
    )
    parser.add_argument(
        "-f",
        "--file",
        help="File to anonymize. Supported files (txt, csv, xlsx)",
    )
    args = parser.parse_args()
    if args.config is None:
        config = gen_default_config()
    else:
        with open(args.config, 'r') as json_file:
            config = json.load(json_file)
    load_and_anonymize(args.file, config)
